export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_MUNICIPALITIES_PENDING = 'REQUEST_MUNICIPALITIES_PENDING';
export const REQUEST_MUNICIPALITIES_SUCCESS = 'REQUEST_MUNICIPALITIES_SUCCESS';
export const REQUEST_MUNICIPALITIES_FAILED = 'REQUEST_MUNICIPALITIES_FAILED';

export const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';
