export const REQUEST_MUNICIPALITIES_PENDING = 'REQUEST_MUNICIPALITIES_PENDING';
export const REQUEST_MUNICIPALITIES_SUCCESS = 'REQUEST_MUNICIPALITIES_SUCCESS';
export const REQUEST_MUNICIPALITIES_FAILED = 'REQUEST_MUNICIPALITIES_FAILED';

export const REQUEST_SELECTED_PENDING = 'REQUEST_SELECTED_PENDING';
export const REQUEST_SELECTED_SUCCESS = 'REQUEST_SELECTED_SUCCESS';
export const REQUEST_SELECTED_FAILED = 'REQUEST_SELECTED_FAILED';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const PIN_MUNICIPALITY = 'PIN_MUNICIPALITY';
export const UNPIN_MUNICIPALITY = 'UNPIN_MUNICIPALITY';
