export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_PROVINCES_PENDING = 'REQUEST_PROVINCES_PENDING';
export const REQUEST_PROVINCES_SUCCESS = 'REQUEST_PROVINCES_SUCCESS';
export const REQUEST_PROVINCES_FAILED = 'REQUEST_PROVINCES_FAILED';
