export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const PIN_MUNICIPALITY = 'PIN_MUNICIPALITY';
export const UNPIN_MUNICIPALITY = 'UNPIN_MUNICIPALITY';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_FAILED = 'GOOGLE_SIGN_IN_FAILED';

export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';
export const EMAIL_SIGN_IN_SUCCESS = 'EMAIL_SIGN_IN_SUCCESS';
export const EMAIL_SIGN_IN_FAILED = 'EMAIL_SIGN_IN_FAILED';
