export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

export const PIN_MUNICIPALITY = 'PIN_MUNICIPALITY';
export const UNPIN_MUNICIPALITY = 'UNPIN_MUNICIPALITY';
export const CLEAR_PINNED = 'CLEAR_PINNED';

export const UPDATE_PINNED_START = 'UPDATE_PINNED_START';
export const UPDATE_PINNED_SUCCESS = 'UPDATE_PINNED_SUCCESS';
export const UPDATE_PINNED_FAILED = 'UPDATE_PINNED_FAILED';
